import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SemesterWithCourses, User } from '@shared/schema';
import { calculateCourseGrade, calculateSemesterGpa, calculateDegreeGpa } from './gpaCalculations';

const semesterTermNames: Record<string, string> = {
  'A': 'Semester A',
  'B': 'Semester B',
  'Summer': 'Summer',
};

export function generateGradeReport(
  semesters: SemesterWithCourses[],
  user: User | null | undefined
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const marginRight = 15;
  const marginLeft = 15;
  const contentWidth = pageWidth - marginRight - marginLeft;

  let yPosition = 20;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('GradeGoal', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('Grade Report', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 15;

  if (user) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const today = new Date().toLocaleDateString('en-US');
    doc.text(`Date: ${today}`, marginLeft, yPosition);
    
    if (user.academicInstitution) {
      yPosition += 6;
      doc.text(`Institution: ${user.academicInstitution}`, marginLeft, yPosition);
    }
  }

  yPosition += 15;

  const overallGpa = calculateDegreeGpa(semesters);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Overall GPA: ${overallGpa !== null ? overallGpa.toFixed(2) : 'N/A'}`, marginLeft, yPosition);

  const totalCredits = semesters.reduce((sum, sem) => 
    sum + sem.courses.reduce((cSum, c) => cSum + c.credits, 0), 0
  );
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`Total Credits: ${totalCredits}`, pageWidth - marginRight - 35, yPosition);

  yPosition += 15;

  const sortedSemesters = [...semesters].sort((a, b) => {
    if (a.academicYear !== b.academicYear) return a.academicYear - b.academicYear;
    const termOrder = { 'A': 0, 'B': 1, 'Summer': 2 };
    return (termOrder[a.term as keyof typeof termOrder] || 0) - 
           (termOrder[b.term as keyof typeof termOrder] || 0);
  });

  for (const semester of sortedSemesters) {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    const semesterGpa = calculateSemesterGpa(semester.courses);
    const semesterCredits = semester.courses.reduce((sum, c) => sum + c.credits, 0);
    const termName = semesterTermNames[semester.term] || semester.term;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Year ${semester.academicYear} - ${termName}`, marginLeft, yPosition);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(
      `GPA: ${semesterGpa !== null ? semesterGpa.toFixed(2) : 'N/A'} | Credits: ${semesterCredits}`,
      pageWidth - marginRight - 45,
      yPosition
    );

    yPosition += 5;

    const tableData = semester.courses.map(course => {
      const grade = calculateCourseGrade(course.gradeComponents);
      return [
        course.name,
        course.credits.toString(),
        grade !== null ? grade.toFixed(1) : '-',
        course.targetGrade !== null && course.targetGrade !== undefined 
          ? course.targetGrade.toFixed(1) 
          : '-',
      ];
    });

    if (tableData.length > 0) {
      autoTable(doc, {
        startY: yPosition,
        head: [['Course Name', 'Credits', 'Grade', 'Target']],
        body: tableData,
        margin: { left: marginLeft, right: marginRight },
        tableWidth: contentWidth,
        headStyles: {
          fillColor: [66, 66, 66],
          textColor: 255,
          fontStyle: 'bold',
          fontSize: 9,
          halign: 'left',
        },
        bodyStyles: {
          fontSize: 9,
          halign: 'left',
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
        columnStyles: {
          0: { cellWidth: contentWidth * 0.45 },
          1: { cellWidth: contentWidth * 0.15, halign: 'center' },
          2: { cellWidth: contentWidth * 0.20, halign: 'center' },
          3: { cellWidth: contentWidth * 0.20, halign: 'center' },
        },
      });

      yPosition = (doc as any).lastAutoTable.finalY + 10;
    } else {
      yPosition += 10;
      doc.setFontSize(9);
      doc.text('No courses in this semester', marginLeft + 5, yPosition);
      yPosition += 10;
    }
  }

  yPosition += 10;
  if (yPosition > 270) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Generated by GradeGoal on ${new Date().toLocaleDateString('en-US')}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  );

  const fileName = `grade-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
